### ISSUE TITLE
Reporting Posts: Add "Report" option to posts 

### ISSUE THREAD

**Issue by Chen3018** [CMU-313/spring24-nodebb-roger#14]
Dependencies: None
Milestones: Sprint 2
Acceptance:
- Users can click "Report" button and enter in text in textbox as reason for report
- Instructors can see visual graphic that indicates post is reported
- Indicators can see reason for report on post

**Comment by tkroening** [comment]
_Note_: I think posts already have something similar to this, it's just called "flagging" instead.

**Comment by tkroening** [comment]
I'll close this issue for now since it would implement a feature that already exists in NodeBB.
